# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "categorias", :force => true do |t|
    t.column "nombre", :string
  end

  create_table "contactos", :force => true do |t|
    t.column "nombre", :string
    t.column "apellidos", :string
    t.column "telefono", :string
    t.column "email", :string
    t.column "direccion", :text
    t.column "categoria_id", :integer
  end

end
