# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "opensuse" do |i|
    i.vm.box = "opensuse/openSUSE-15.0-x86_64"
    i.vm.hostname = "profesor42g"
    i.vm.network "public_network", bridge: [
      "enp2s0",
      "wlp1s0",
    ]
    i.vm.provider "virtualbox" do |v|
      v.name = 'opensuse-leap15'
      v.memory = 2048
    end
  end
end
