#!/usr/bin/env ruby
# Target:
# * Show current network configuration: IP, mask, interface name
# Changes:
# * Execute command wiht system(command)
# * Filter only real IP with grep and grep -v
# * Save command output using %x[command]
# * Pretty and clear output
# * It's easy then show if_name
# * Print colors using Rainbow gem (gem install rainbow)
# * Show gateway and verify Internet access
# * Organize code using functions
# * Organize code using gems. Remove extension from filename.
# * Verify DNS server configuration 

require_relative '10-netconf-lib'
display_network_information
