#!/usr/bin/env ruby
# Target:
# * Show current network configuration: IP, mask, interface name
# Changes:
# * Execute command wiht system(command)
# * Filter only real IP with grep and grep -v
# * Save command output using %x[command]
# * Pretty and clear output
# * It's easy then show if_name
# * Print colors using Rainbow gem (gem install rainbow)
# * Show gateway and verify Internet access
# * Organize code using functions
# * Organize code using gems. Remove extension from filename.
# * Verify DNS server configuration
# * Learn about IP configuration
#     * URL: https://www.tecmint.com/ip-command-examples/
#
# Command to assign a IP Address to Specific Interface
# ip addr add 192.168.50.5 dev eth1
#
# How to Remove an IP Address
# ip addr del 192.168.50.5/24 dev eth1
#
# How to Enable Network Interface
# ip link set eth1 up
#
# How to Disable Network Interface
# ip link set eth1 down
#
# How do I Check Route Table?
# ip route show

require_relative '11-netconf-lib'
display_network_information

data = { :device => 'enp0s20u2',
         :new_ip => '172.31.16.0/16' }
set_network_information(data)
display_network_information
