# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |i|
    i.vm.box = "ubuntu/bionic64"
    i.vm.hostname = "profesor42u"
    i.vm.network "public_network", bridge: [ "eth0" ]
    i.vm.provider "virtualbox" do |v|
      v.name = 'ubuntu-bionic64'
      v.memory = 2048
    end
  end
end

