# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "categorias", :force => true do |t|
    t.column "nombre",    :string
    t.column "parent_id", :integer
  end

  create_table "categorias_fotos", :id => false, :force => true do |t|
    t.column "categoria_id", :integer
    t.column "foto_id",      :integer
  end

  create_table "diapositivas", :force => true do |t|
    t.column "posicion", :integer
    t.column "foto_id",  :integer
    t.column "pase_id",  :integer
  end

  create_table "fotos", :force => true do |t|
    t.column "fichero",        :string
    t.column "fecha_creacion", :datetime
    t.column "thumbnail",      :string
    t.column "descripcion",    :string
  end

  create_table "pases", :force => true do |t|
    t.column "nombre",    :string
    t.column "creado_en", :datetime
  end

end
