#!/usr/bin/ruby

### The following adjusts the load path so that the correct version of
### a self-contained package is found, no matter where the script is
### run from. 
require 'pathname'
$:.unshift((Pathname.new(__FILE__).parent.parent + 'lib').to_s)
require '!REPLACE_ME_FILE!/third-party/s4t-utils/load-path-auto-adjuster'


require 's4t-utils'
include S4tUtils

require '!REPLACE_ME_FILE!'
# You probably want to include your module as well, but I won't assume
# that. 
# include !REPLACE_ME_MODULE!

if $0 == __FILE__
  with_pleasant_exceptions do
     # Your program here.
  end
end
