# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "noticias", :force => true do |t|
    t.column "titulo", :string
    t.column "contenido", :text
  end

  create_table "usuarios", :force => true do |t|
    t.column "nombre", :string
    t.column "clave", :string
  end

end
