# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "opensuse-kde" do |i|
    i.vm.box = "microlinux/opensuse-15.3-kde"
    i.vm.hostname = "kde42"
    #i.vm.network "public_network", bridge: [ "eth1" ]
    i.vm.network :forwarded_port, guest: 22, host: 2232
    i.vm.synced_folder "./", "/vagrant"
    i.vm.provision "shell", inline: <<-SHELL
      zypper refresh
      zypper in -y vim tree nmap
    SHELL
    i.vm.provider "virtualbox" do |v|
      v.name = 'opensuse-kde'
      v.memory = 2048
    end
  end
end
