#!/usr/bin/ruby
#
# URL sed:
# http://www.sysadmit.com/2015/07/linux-reemplazar-texto-en-archivos-con-sed.html
#
# Esquema:
# * hostname y /etc/hosts
# * interfaces de red
# * DNS, gateway
# * Usuario, SSHServer, PermitRootLogin Yes

require 'progress_bar'

bar = ProgressBar.new

AULA='18'
NUMBER='43'
USERNAME='alumno1'
PASSWORD='alumno1617'

IP="172.#{AULA}.#{NUMBER}.32"
HOSTNAME="PC#{NUMBER}"
DOMAINNAME="curso1617"
MASK="16"
DNS="8.8.4.4"
GATEWAY="172.#{AULA}.0.1"

currentuser=`whoami`.strip
if currentuser!='root'
  puts "Se requiere ejecutar con usuario root"
  exit 1
end

# echo "pepito" > /etc/hostname
# echo "172.18.3.109   pepito.curso1617   pepito" >> /etc/hosts
system("echo '#{HOSTNAME}.#{DOMAINNAME}' > /etc/hostname")
system("echo '#{IP}   #{HOSTNAME}.#{DOMAINNAME}   #{HOSTNAME}' >> /etc/hosts")
sleep 0.1
bar.increment! 25

# /etc/sysconfig/network/ifcfg-eth0
# BOOTPROTO='static'
# IPADDR='IP/MASK'
# STARTMODE='auto'
filename="/etc/sysconfig/network/ifcfg-eth0"
system("echo \"BOOTPROTO='static'\" > #{filename}")
bar.increment! 4.16
system("echo \"IPADDR='#{IP}/#{MASK}'\" >> #{filename}")
bar.increment! 4.16
system("echo \"STARTMODE='auto'\" >> #{filename}")
bar.increment! 4.17
system("echo \"GATEWAY='#{GATEWAY}'\" >> #{filename}")
bar.increment! 4.17
#system("systemctl restart network")
system("ifdown eth0 > /dev/null")
bar.increment! 4.17
system("ifup eth0 > /dev/null")
bar.increment! 4.17
sleep 0.1

# /etc/resolv.conf
# Generated by NetworkManager
# search vargas suse
# nameserver 80.58.61.250
# nameserver 172.19.0.1
# nameserver 172.18.0.1
filename="/etc/resolv.conf"
system("echo \"# Generador por nosotros\" > #{filename}")
bar.increment! 6.25
system("echo \"search #{DOMAINNAME}\" >> #{filename}")
bar.increment! 6.25
system("echo \"nameserver #{DNS}\" >> #{filename}")
bar.increment! 6.25
#system("route del default gw 10.3.0.2 eth1")
system("route add default gw #{GATEWAY} eth0")
bar.increment! 6.25
sleep 0.1

cmd = `id #{USERNAME}|wc -l`
if cmd.to_i==0
  system("useradd -d /home/#{USERNAME} -m #{USERNAME}")
end
bar.increment! 5
system("echo \"#{USERNAME}:#{PASSWORD}\" | chpasswd")
bar.increment! 5
##SSH server
packages = [ 'openssh', 'tree' ]
packages.each do |name|
  cmd = `zypper info #{name}|grep Instalado|grep Si|wc -l`
  if cmd.to_i==0
    `zypper -n install #{name}`
  end
end
bar.increment! 5
system("echo \"PermitRootLogin Yes\" >> /etc/ssh/sshd_config")
bar.increment! 10
