#!/usr/bin/ruby

# Esquema:
# * hostname, etc host
# * interfaces de red
# * dns gateway
# * usuario, opensshhserver permitrootlogin yes

param = {}
content = `cat configurar2.data`
filas = content.split("\n")
filas.each do |fila|
  rows = fila.split(",")
  param[rows[0].strip]=rows[1].strip
end

varnames = ['aula','number','username','password']
varnames.each do |varname|
  if param[varname]==nil
    print "Escribe valor para <#{varname}> "
    param[varname]=gets.strip
  end
end

AULA=param['aula']
NUMBER=param['number']
USERNAME=param['username']
PASSWORD=param['password']

IP="172.#{AULA}.#{NUMBER}.32"
HOSTNAME="PC#{NUMBER}"
DOMAINNAME="curso1617"
MASK="16"
DNS="8.8.4.4"
GATEWAY="172.#{AULA}.0.1"

def check_user_root
  currentuser=`whoami`.strip
  if currentuser!='root'
    puts "Se requiere ejecutar con usuario root"
    exit 1
  end
end

def update_hostname(ip, hostname,domainname)
  # echo "pepito" > /etc/hostname
  # echo "172.18.3.109   pepito.curso1617   pepito" >> /etc/hosts
  system("echo '#{hostname}.#{domainname}' > /etc/hostname")
  system("echo '#{ip}   #{hostname}.#{domainname}   #{hostname}' >> /etc/hosts")
end

def update_network(ip,mask,gateway)
  # /etc/sysconfig/network/ifcfg-eth0
  # BOOTPROTO='static'
  # IPADDR='IP/MASK'
  # STARTMODE='auto'
  filename="/etc/sysconfig/network/ifcfg-eth0"
  system("echo \"BOOTPROTO='static'\" > #{filename}")
  system("echo \"IPADDR='#{ip}/#{mask}'\" >> #{filename}")
  system("echo \"STARTMODE='auto'\" >> #{filename}")
  system("echo \"GATEWAY='#{gateway}'\" >> #{filename}")
  #system("systemctl restart network")
  system("ifdown eth0 > /dev/null")
  system("ifup eth0 > /dev/null")
end

def update_dns(domain,dns,gateway)
  # /etc/resolv.conf
  # Generated by NetworkManager
  # search vargas suse
  # nameserver 80.58.61.250
  # nameserver 172.19.0.1
  # nameserver 172.18.0.1
  filename="/etc/resolv.conf"
  system("echo \"# Generador por nosotros\" > #{filename}")
  system("echo \"search #{domain}\" >> #{filename}")
  system("echo \"nameserver #{dns}\" >> #{filename}")
  #system("route del default gw 10.3.0.2 eth1")
  system("route add default gw #{gateway} eth0")
end

def create_user(username,password)
  cmd = `id #{username}|wc -l`
  if cmd.to_i==0
    system("useradd -d /home/#{username} -m #{username}")
  end
  system("echo \"#{username}:#{password}\" | chpasswd")
end

def update_ssh
  ##SSH server
  packages = [ 'openssh', 'tree' ]
  packages.each do |name|
    cmd = `zypper info #{name}|grep Instalado|grep Si|wc -l`
    if cmd.to_i==0
      `zypper -n install #{name}`
    end
  end
  system("echo \"PermitRootLogin Yes\" >> /etc/ssh/sshd_config")
end

check_user_root
update_hostname(IP, HOSTNAME, DOMAINNAME)
update_network(IP,MASK,GATEWAY)
update_dns(DOMAINNAME,DNS,GATEWAY)
create_user(USERNAME,PASSWORD)
update_ssh

filename="configurar2.data"
varnames = ['aula','number','username','password']
`rm #{filename}`
varnames.each do |varname|
  `echo "#{varname},#{param[varname]}" >> #{filename}`
end
