#Fichero: Makefile
#Compilar con:
# $make

CFLAGS = -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer
#CFLAGS = -L/usr/include/SDL
CC = g++

FUENTE = principal.c
EJECUTABLE = juego

main:
	$(CC) $(FUENTE) $(CFLAGS) -o $(EJECUTABLE)
	
