# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ldap42" do |i|
    i.vm.box = "generic/opensuse15"
    i.vm.hostname = "ldap42.curso1920"
    i.vm.network "public_network", bridge: [
      "enp2s0",
      "wlp1s0",
    ]

    i.vm.provision "shell", inline: <<-SHELL
      zypper in -y vim tree nmap
      zypper in -y 389-ds
    SHELL
    i.vm.provider "virtualbox" do |v|
      v.name = 'ldap42'
      v.memory = 2048
    end
  end
end
