# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "windows7" do |i|
    i.vm.box = "opentable/win-7-professional-amd64-nocm"
    i.vm.box_version = "1.0.0"
    i.vm.hostname = "profesor42w7"
    i.vm.network "public_network", bridge: [ "eth0" ]
    i.vm.network :forwarded_port, guest: 80, host: 8081
    i.vm.provider "virtualbox" do |v|
      v.name = "windows7-pro64"
      v.memory = 2048
    end

#    i.ssh.username = "IEUser"
#    i.ssh.password = "Passw0rd"
  end
end
