# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "debian10" do |i|
    i.vm.box = "generic/debian10"
    i.vm.hostname = "profesor42d.curso1920"
    i.vm.network "public_network", bridge: [ "eth0" ]
    i.vm.network :forwarded_port, guest: 22, host: 2241
    i.vm.synced_folder "./", "/vagrant"
    i.vm.provision "shell", inline: <<-SHELL
      apt-get update 
      apt-get install -y vim tree nmap
    SHELL
    i.vm.provider "virtualbox" do |v|
      v.name = 'debian10'
      v.memory = 2048
    end
  end
end
