# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "salt-master" do |i|
    i.vm.box = "generic/opensuse15"
    i.vm.hostname = "salt-master"
    i.vm.network "public_network", bridge: [
      "wlp1s0",
      "enp2s0",
    ]

    i.vm.provision "shell", inline: <<-SHELL
    zypper install -y tree
    zypper install -y vim
    SHELL
    i.vm.provider "virtualbox" do |v|
      v.name = 'salt-master'
      v.memory = 2048
    end
  end
end
