# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 10) do

  create_table "alumnos", :force => true do |t|
    t.column "nombre",    :string
    t.column "apellidos", :string
    t.column "dni",       :string
    t.column "correo",    :string
    t.column "telefono",  :string
    t.column "foto",      :string
  end

  create_table "alumnos_grupos", :id => false, :force => true do |t|
    t.column "grupo_id",  :integer
    t.column "alumno_id", :integer
  end

  create_table "aulas", :force => true do |t|
    t.column "nombre",      :string
    t.column "foto",        :string
    t.column "descripcion", :string
    t.column "fecha_um",    :datetime
  end

  create_table "clases", :force => true do |t|
    t.column "curso_id",     :integer
    t.column "aula_id",      :integer
    t.column "profesor_id",  :integer
    t.column "modulo_id",    :integer
    t.column "grupo_id",     :integer
    t.column "diasemana_id", :integer
    t.column "hora_id",      :integer
  end

  create_table "cursos", :force => true do |t|
    t.column "nombre",        :string
    t.column "inicio_clases", :datetime
    t.column "fin_clases",    :datetime
  end

  create_table "departamentos", :force => true do |t|
    t.column "nombre", :string
  end

  create_table "festivos", :force => true do |t|
    t.column "curso_id",     :integer
    t.column "fecha_inicio", :datetime
    t.column "fecha_fin",    :datetime
    t.column "descripcion",  :string
  end

  create_table "grupos", :force => true do |t|
    t.column "curso_id", :integer
    t.column "codigo",   :string
  end

  create_table "modulos", :force => true do |t|
    t.column "codigo",                :string
    t.column "nombre",                :string
    t.column "num_horas_total_boc",   :integer
    t.column "num_horas_semanal_boc", :integer
  end

  create_table "profesors", :force => true do |t|
    t.column "nombre",          :string
    t.column "apellidos",       :string
    t.column "dni",             :string
    t.column "correo",          :string
    t.column "telefono",        :string
    t.column "departamento_id", :integer
  end

end
