#---
# Excerpted from "Everyday Scripting in Ruby"
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/bmsft for more book information.
#---
# DO NOT EDIT
# This file is auto-generated by build scripts.
# See:  rake update_version
module Gem
  RubyGemsVersion = '0.8.11'
end
