#insert into categorias values (1, 'All', null);
insert into categorias values (2, 'People',  1);
insert into categorias values (3, 'Animals', 1);
insert into categorias values (4, 'Places',  1);
insert into categorias values (5, 'Things',  1);
insert into categorias values (6, 'Friends', 2);
insert into categorias values (7, 'Family', 2);
insert into categorias_fotos values (4, 1);
insert into categorias_fotos values (3, 2);
insert into categorias_fotos values (3, 3);
insert into categorias_fotos values (4, 4);
insert into categorias_fotos values (5, 5);
insert into categorias_fotos values (3, 6);
insert into categorias_fotos values (2, 7);
insert into categorias_fotos values (4, 8);
insert into categorias_fotos values (4, 9);
insert into categorias_fotos values (4, 7);
