/*
 * VentanaTerminalGnome.java
 *
 * Created on 15 de enero de 2008, 18:42
 */
package terminal.ui.gui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import terminal.shell.*;


/**
 *
 * @author  david
 */
public class VentanaTerminalGnome extends javax.swing.JFrame implements ActionListener {

    public static final long serialVersionUID = 1;

    /** Creates new form VentanaTerminalGnome */
    public VentanaTerminalGnome() {
        initComponents();
        this.inicializar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSolapas = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextPane();
        mnuBarra = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuAbrirSolapa = new javax.swing.JMenuItem();
        mnuCerrarSolapa = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        mnuCerrarTerminal = new javax.swing.JMenuItem();
        mnuEditar = new javax.swing.JMenu();
        mnuCopiar = new javax.swing.JMenuItem();
        mnuPegar = new javax.swing.JMenuItem();
        mnuPreferencias = new javax.swing.JMenu();
        mnuLookAndFeel = new javax.swing.JMenu();
        mnuLAFJava = new javax.swing.JRadioButtonMenuItem();
        mnuLAFWindows = new javax.swing.JRadioButtonMenuItem();
        mnuLAFMotif = new javax.swing.JRadioButtonMenuItem();
        mnuEstablecerTitulo = new javax.swing.JMenu();
        mnuTituloVentana = new javax.swing.JMenuItem();
        mnuTituloSolapa = new javax.swing.JMenuItem();
        mnuTexto = new javax.swing.JMenuItem();
        mnuColor = new javax.swing.JMenu();
        mnuColorFondo = new javax.swing.JMenuItem();
        mnuColorTexto = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        mnuAmpliar = new javax.swing.JMenuItem();
        mnuReducir = new javax.swing.JMenuItem();
        mnuTamanoOriginal = new javax.swing.JMenuItem();
        mnuSolapas = new javax.swing.JMenu();
        mnuSolapaAnterior = new javax.swing.JMenuItem();
        mnuSolapaSiguiente = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JSeparator();
        mnuMoverSolapaIzquierda = new javax.swing.JMenuItem();
        mnuMoverSolapaDerecha = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        mnuTerminal1 = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuAcercaDe = new javax.swing.JMenuItem();
        mnuSalirAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Imitando a gnome-terminal");
        setName("frmVentana"); // NOI18N

        pnlSolapas.setName("Acerca de"); // NOI18N
        pnlSolapas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pnlSolapasStateChanged(evt);
            }
        });

        txtDescripcion.setContentType("text/html");
        txtDescripcion.setText("<html>\n  <head>\n\n  </head>\n  <body>\n      <h1>Interfaz Gráfico de Consola Virtual</h1>\n    <p style=\"margin-top: 0\">Esta es una aplicación desarrollada en java cuyo propósito \nes el de crear una interfaz gráfico sobre la clase ConsolaVirtual desarrollada en la práctica anterior.</p>\n<p><b>Autor:</b> David Vargas dvargas@canarias.org</p>\n<p><b>Versión:</b>0.1.0 20080120</p>\n  </body>\n</html>\n");
        txtDescripcion.setFocusable(false);
        txtDescripcion.setMaximumSize(new java.awt.Dimension(600, 400));
        txtDescripcion.setMinimumSize(new java.awt.Dimension(600, 400));
        jScrollPane2.setViewportView(txtDescripcion);

        pnlSolapas.addTab("tab2", jScrollPane2);

        getContentPane().add(pnlSolapas, java.awt.BorderLayout.CENTER);
        pnlSolapas.getAccessibleContext().setAccessibleName("");
        pnlSolapas.getAccessibleContext().setAccessibleDescription("Descripción");

        mnuBarra.setName("mnuBarra"); // NOI18N

        mnuArchivo.setText("Archivo");

        mnuAbrirSolapa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuAbrirSolapa.setText("Abrir solapa");
        mnuAbrirSolapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAbrirSolapaActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuAbrirSolapa);

        mnuCerrarSolapa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuCerrarSolapa.setText("Cerrar solapa");
        mnuCerrarSolapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarSolapaActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuCerrarSolapa);
        mnuArchivo.add(jSeparator2);

        mnuCerrarTerminal.setText("Cerrar terminal");
        mnuArchivo.add(mnuCerrarTerminal);

        mnuBarra.add(mnuArchivo);

        mnuEditar.setText("Editar");

        mnuCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuCopiar.setText("Copiar");
        mnuCopiar.setEnabled(false);
        mnuEditar.add(mnuCopiar);

        mnuPegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuPegar.setText("Pegar");
        mnuPegar.setEnabled(false);
        mnuEditar.add(mnuPegar);

        mnuBarra.add(mnuEditar);

        mnuPreferencias.setText("Preferencias");

        mnuLookAndFeel.setText("Look and Feel");

        mnuLAFJava.setSelected(true);
        mnuLAFJava.setText("Java");
        mnuLookAndFeel.add(mnuLAFJava);

        mnuLAFWindows.setText("MS-Windows");
        mnuLookAndFeel.add(mnuLAFWindows);

        mnuLAFMotif.setText("Motif");
        mnuLookAndFeel.add(mnuLAFMotif);

        mnuPreferencias.add(mnuLookAndFeel);

        mnuEstablecerTitulo.setText("Establecer título");

        mnuTituloVentana.setText("Establecer el título de la ventana");
        mnuEstablecerTitulo.add(mnuTituloVentana);

        mnuTituloSolapa.setText("Establecer el título de la solapa");
        mnuEstablecerTitulo.add(mnuTituloSolapa);

        mnuPreferencias.add(mnuEstablecerTitulo);

        mnuTexto.setText("Texto");
        mnuPreferencias.add(mnuTexto);

        mnuColor.setText("Color");

        mnuColorFondo.setText("Color del fondo");
        mnuColor.add(mnuColorFondo);

        mnuColorTexto.setText("Color del texto");
        mnuColor.add(mnuColorTexto);

        mnuPreferencias.add(mnuColor);
        mnuPreferencias.add(jSeparator3);

        mnuAmpliar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PLUS, java.awt.event.InputEvent.CTRL_MASK));
        mnuAmpliar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/terminal/ui/gui/viewmag+.png"))); // NOI18N
        mnuAmpliar.setText("Ampliar");
        mnuPreferencias.add(mnuAmpliar);

        mnuReducir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_MINUS, java.awt.event.InputEvent.CTRL_MASK));
        mnuReducir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/terminal/ui/gui/viewmag-.png"))); // NOI18N
        mnuReducir.setText("Reducir");
        mnuPreferencias.add(mnuReducir);

        mnuTamanoOriginal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.CTRL_MASK));
        mnuTamanoOriginal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/terminal/ui/gui/viewmag1.png"))); // NOI18N
        mnuTamanoOriginal.setText("Tamaño original");
        mnuPreferencias.add(mnuTamanoOriginal);

        mnuBarra.add(mnuPreferencias);

        mnuSolapas.setText("Solapas");

        mnuSolapaAnterior.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuSolapaAnterior.setText("Solapa anterior");
        mnuSolapaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSolapaAnteriorActionPerformed(evt);
            }
        });
        mnuSolapas.add(mnuSolapaAnterior);

        mnuSolapaSiguiente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuSolapaSiguiente.setText("Solapa siguiente");
        mnuSolapaSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSolapaSiguienteActionPerformed(evt);
            }
        });
        mnuSolapas.add(mnuSolapaSiguiente);
        mnuSolapas.add(jSeparator6);

        mnuMoverSolapaIzquierda.setText("Mover solapa a la izquierda");
        mnuSolapas.add(mnuMoverSolapaIzquierda);

        mnuMoverSolapaDerecha.setText("Mover solapa a la derecha");
        mnuSolapas.add(mnuMoverSolapaDerecha);
        mnuSolapas.add(jSeparator1);

        mnuTerminal1.setText("Terminal 1");
        mnuSolapas.add(mnuTerminal1);

        mnuBarra.add(mnuSolapas);

        mnuAyuda.setText("Ayuda");

        mnuAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/terminal/ui/gui/help.png"))); // NOI18N
        mnuAcercaDe.setText("Acerca de");
        mnuAyuda.add(mnuAcercaDe);

        mnuSalirAyuda.setText("Salir");
        mnuAyuda.add(mnuSalirAyuda);

        mnuBarra.add(mnuAyuda);

        setJMenuBar(mnuBarra);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void pnlSolapasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pnlSolapasStateChanged
        // TODO add your handling code here:
        //System.out.println(this.pnlSolapas.getTabCount());
    //this.pnlSolapas.getTabComponentAt(0).setName("hola");
    }//GEN-LAST:event_pnlSolapasStateChanged

    private void mnuAbrirSolapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAbrirSolapaActionPerformed
        int index = 1 + this.pnlSolapas.getTabCount();
        PanelTerminal pt = new PanelTerminal();
        if (index==2) {
            pt.setShell(new ShellAPIjava());
        } else if (index==3) {
            pt.setShell(new ShellExec());
        } else if (index==4) {
            pt.setShell(new ShellClienteRemoto());
        } else {
            pt.setShell(new ShellExec());
        }
        this.pnlSolapas.addTab("Terminal " + index, pt);
    }//GEN-LAST:event_mnuAbrirSolapaActionPerformed

    private void mnuCerrarSolapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarSolapaActionPerformed
        // TODO add your handling code here:
        int index = this.pnlSolapas.getSelectedIndex();
    }//GEN-LAST:event_mnuCerrarSolapaActionPerformed

    private void mnuSolapaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSolapaAnteriorActionPerformed
        int index = this.pnlSolapas.getSelectedIndex();
        if (index>0) index--;
        this.pnlSolapas.setSelectedIndex(index);
    }//GEN-LAST:event_mnuSolapaAnteriorActionPerformed

    private void mnuSolapaSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSolapaSiguienteActionPerformed
        int index = this.pnlSolapas.getSelectedIndex();
        if ((index+1)<this.pnlSolapas.getTabCount()) index++;
        this.pnlSolapas.setSelectedIndex(index);
    }//GEN-LAST:event_mnuSolapaSiguienteActionPerformed

    private void inicializar() {
        //JFrame
        this.setBounds(100, 100, 800, 600);

        this.pnlSolapas.setTitleAt(0, "Terminal 1");

        this.mnuLAFJava.addActionListener(this);
        this.mnuLAFWindows.addActionListener(this);
        this.mnuLAFMotif.addActionListener(this);
    }

    public void actionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
        System.out.print(evt.getActionCommand());
        if (evt.getActionCommand().equals("Java")) {
            this.setAspecto(0);
        } else if (evt.getActionCommand().equals("MS-Windows")) {
            this.setAspecto(1);
        } else if (evt.getActionCommand().equals("Motif")) {
            this.setAspecto(2);
        }
    }

    private void setAspecto(int tipo) {
        String aspecto[] = new String[3];
        aspecto[0] = "javax.swing.plaf.metal.MetalLookAndFeel";
        aspecto[1] = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
        aspecto[2] = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
        this.mnuLAFJava.setSelected(false);
        this.mnuLAFWindows.setSelected(false);
        this.mnuLAFMotif.setSelected(false);
        if (tipo==0) this.mnuLAFJava.setSelected(true);
        if (tipo==1) this.mnuLAFWindows.setSelected(true);
        if (tipo==2) this.mnuLAFMotif.setSelected(true);
        
        try {
            UIManager.setLookAndFeel(aspecto[tipo]);
            SwingUtilities.updateComponentTreeUI(this);
            this.pack();
            this.setBounds(100, 100, 800, 600);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se puede cambiar el aspecto " + e, "Fallo GUI", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VentanaTerminalGnome().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JMenuItem mnuAbrirSolapa;
    private javax.swing.JMenuItem mnuAcercaDe;
    private javax.swing.JMenuItem mnuAmpliar;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuBar mnuBarra;
    private javax.swing.JMenuItem mnuCerrarSolapa;
    private javax.swing.JMenuItem mnuCerrarTerminal;
    private javax.swing.JMenu mnuColor;
    private javax.swing.JMenuItem mnuColorFondo;
    private javax.swing.JMenuItem mnuColorTexto;
    private javax.swing.JMenuItem mnuCopiar;
    private javax.swing.JMenu mnuEditar;
    private javax.swing.JMenu mnuEstablecerTitulo;
    private javax.swing.JRadioButtonMenuItem mnuLAFJava;
    private javax.swing.JRadioButtonMenuItem mnuLAFMotif;
    private javax.swing.JRadioButtonMenuItem mnuLAFWindows;
    private javax.swing.JMenu mnuLookAndFeel;
    private javax.swing.JMenuItem mnuMoverSolapaDerecha;
    private javax.swing.JMenuItem mnuMoverSolapaIzquierda;
    private javax.swing.JMenuItem mnuPegar;
    private javax.swing.JMenu mnuPreferencias;
    private javax.swing.JMenuItem mnuReducir;
    private javax.swing.JMenuItem mnuSalirAyuda;
    private javax.swing.JMenuItem mnuSolapaAnterior;
    private javax.swing.JMenuItem mnuSolapaSiguiente;
    private javax.swing.JMenu mnuSolapas;
    private javax.swing.JMenuItem mnuTamanoOriginal;
    private javax.swing.JMenuItem mnuTerminal1;
    private javax.swing.JMenuItem mnuTexto;
    private javax.swing.JMenuItem mnuTituloSolapa;
    private javax.swing.JMenuItem mnuTituloVentana;
    private javax.swing.JTabbedPane pnlSolapas;
    private javax.swing.JTextPane txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
