Vagrant.configure("2") do |config|
end
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "manjaro" do |i|
	config.vm.box = "marashni/manjaro64"
	config.vm.box_version = "0.0.1"
  config.vm.hostname = "manjaro42"
  #config.vm.network "public_network", bridge: [ "eth1" ]
  config.vm.network :forwarded_port, guest: 22, host: 2231
  config.vm.synced_folder "./", "/vagrant"
  config.vm.provision "shell", inline: <<-SHELL
    zypper refresh
    zypper in -y vim tree nmap
  SHELL
  config.vm.provider "virtualbox" do |vm|
    vm.name = 'manjaro'
    vm.memory = 2048
  end
  end
end
